image: alpine:latest

stages:
  - test
  - build
  - deploy

before_script:
  - export GOPATH=/cache/go


## BACKEND

Test Backend:
  stage: test
  image: golang:latest
  allow_failure: true
  only:
    refs:
      - master
  script:
    - cd backend
    - go mod download
    - go test -cover $(go list ./... | grep -v /vendor/)

Lint Backend:
  stage: test
  image: golang:latest
  allow_failure: true
  only:
    refs:
      - master
  script:
    - cd backend
    - go mod download
    - go get -u golang.org/x/lint/golint
    - /cache/go/bin/golint -set_exit_status $(go list ./... | grep -v /vendor/)

Build Backend:
  stage: build
  image: golang:latest
  only:
    refs:
      - master
  script:
    - cd backend
    - go build -ldflags="-s -w" wtfd.go
  artifacts:
    paths:
      - backend/wtfd

## FRONTEND

Build Frontend:
  stage: build
  image: node:latest
  only:
    refs:
      - master
  script:
    - cd frontend
    - make clean
    - make
  cache:
    paths:
      - frontend/build
      - frontend/node_modules

pages:
  stage: deploy
  only:
    refs:
      - master
  script:
    - cp -vr frontend/build/. public
  cache:
    paths:
      - frontend/build

